---
site_name: Home Panel Docs
site_description: A touch-compatible web-app for controlling the home
site_author: Timmo
site_url: https://home-panel-docs.timmo.dev/

# Repository
repo_name: timmo001/home-panel
repo_url: https://github.com/timmo001/home-panel
edit_uri: "https://github.com/timmo001/home-panel/edit/master/documentation/docs"

# Copyright
copyright: "Copyright &copy; Timmo"

# Configuration
theme:
  name: "material"
  language: "en"
  palette:
    scheme: slate
    primary: "blue grey"
    accent: indigo
  font:
    text: "Roboto"
    code: "Roboto Mono"
  favicon: "favicon.ico"
  logo: "logo.svg"

# Customization
extra:
  search:
    separator: '[\s\-\.]+'
    lang:
      - en
  social:
    - icon: fontawesome/brands/github-alt
      link: "https://github.com/timmo001/home-panel"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/timmo001"

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Pages
nav:
  - Overview: index.md
  - Getting Started:
      - Setup: setup.md
      - Login: login.md
      - Home Assistant: home-assistant.md
  - Configuration:
      - Configuration UI: configui.md
      - Configuration Screen: configuration.md
  - Showcase:
      - Contributing: showcase/contributing.md
      - Timmo's Example Theme: showcase/timmo/timmo.md
  - Frequently Asked Questions: faq.md
  - Troubleshooting: troubleshooting.md
  - Posting an Issue: issue-posting.md
  - Contributing: contributing.md
  - License: license.md
